export const GAME = {
  ELITE_INTERVAL: 10,
  BOSS_INTERVAL: 50,
  QUALITATIVE_UPGRADE_INTERVAL: 100,
  BUFF_SELECTION_INTERVAL: 5,

  BASE_ENEMY_HP: 100,
  HP_SCALE_PER_FLOOR: 1.05,
  ELITE_HP_MULTIPLIER: 5,
  ELITE_DAMAGE_MULTIPLIER: 2,
  BOSS_HP_MULTIPLIER: 20,
  BOSS_DAMAGE_MULTIPLIER: 5,

  QUALITATIVE_HP_JUMP: 3,
  QUALITATIVE_DAMAGE_JUMP: 2,

  COINS_PER_FLOOR: 10,
  BOSS_GEM_REWARD: 5,

  TOKEN_LENGTH: 6,
  TOKEN_EXPIRY_MINUTES: 5,

  AUTO_ATTACK_INTERVAL: 1.0,
  ENEMY_ATTACK_INTERVAL: 1.5,

  SKILL_COUNT: 3,
  SKILL_COOLDOWNS: [5, 8, 12],
  SKILL_DAMAGE_MULTIPLIERS: [1.5, 2.0, 3.0],

  BASE_PLAYER_HP: 500,
  BASE_PLAYER_ATTACK: 50,
  BASE_PLAYER_DEFENSE: 10,
} as const;
